name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Print Git User
        run: echo $GIT_USER

      - name: Print Git Email
        run: echo $GIT_EMAIL

      - name: Deploy to GitHub Pages
        run: npm run build
